### ISSUE TITLE
Indented <style> tags cause every line to report an indentation error

### ISSUE THREAD

**Issue by unikitty37** [sourceboat/sass-lint-vue#11]
I have the following section in a component:

```vue
<style lang="scss" scoped>
  @import '../variables';

  nav {
    margin-top: 0.5rem;
    padding-left: 2rem;
    padding-right: 0.75rem;
    width: calc(100% - 8rem);
    max-width: 70%;
  }
</style>
```

However, every line produces a warning about indentation, saying it expected to find 2 spaces fewer than there actually are:

```
  113:3  indentation          Expected indentation of 0 space but found 2.
  115:3  indentation          Expected indentation of 0 space but found 2.
  116:5  indentation          Expected indentation of 2 space but found 4.
  117:5  indentation          Expected indentation of 2 space but found 4.
  118:5  indentation          Expected indentation of 2 space but found 4.
  119:5  indentation          Expected indentation of 2 space but found 4.
  120:5  indentation          Expected indentation of 2 space but found 4.
```

I can work around this by not indenting the `<style>` tag's contents, but that is inconsistent with every other tag in the file!

Could sass-lint-vue (perhaps optionally) find the common indentation and strip it before passing the code to sass-lint? I can't see a way to configure sass-lint to do this, and I don't want to disable indentation checking completely…

(One gotcha is that, in the example above, the line after the `@import` is *completely* blank, and does not contain two spaces — so lines matching `/^$/` shouldn't affect the calculation :)

**Comment by krns** [comment]
Thanks for sharing your idea. Looks like a nice enhancement but currently we have no plans to implement this. Nevertheless, you could submit a pull request.

**Comment by pehbehbeh** [comment]
This project is not actively maintained anymore. Use it at your own risk. The underlying library [sass-lint](https://github.com/sasstools/sass-lint) is  unmaintained. We recommend using [stylelint](https://vue-loader.vuejs.org/guide/linting.html#stylelint) to lint your single file components directly.
