### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by brophdawg11** [sourceboat/sass-lint-vue#12]
Can the latest versions of this package be published to the `npm` registry?  There is a `0.3.2` tag in the repo, but `npm info sass-lint-vue` shows the latest release as `0.2.1`?

For now, the workaround is to use `"sass-lint-vue": "github:sourceboat/sass-lint-vue#0.3.2"`

**Comment by krns** [comment]
Ah, thanks for the reminder, will publish it tomorrow!
