### ISSUE TITLE
Is it possible to throw an error after a specified number of warnings?

### ISSUE THREAD

**Issue by stevehealy** [sourceboat/sass-lint-vue#23]
Similar to what can be done with sass-lint, is it possible to throw an error after a specified number of warnings?

For example, in `.sass-lint.yml` I can set the following:

```
options:
  # Raise an error if more than x warnings are generated
  max-warnings: 15
```

Which results in the following at run-time when I use sass-lint...

```
throw new exceptions.MaxWarningsExceededError(
MaxWarningsExceededError: Number of warnings (1051) exceeds the allowed maximum of 15.
```

I'm not seeing this with sass-lint-vue so far.
The docs mention using `.sass-lint.yml` as a feature, but I don't see an example of how to use this?

**Comment by pehbehbeh** [comment]
Hi @stevehealy, we have no experience with the `max-warnings` setting and are not using it ourselves. But you can simply drop a `.sass-lint.yml` file in the root of your project folder. `sass-lint-vue` will auto-detect the file.

**Comment by stevehealy** [comment]
Hi @pehbehbeh - yes, I already have the `.sass-lint.yml` file, but the `max-warnings` setting doesn't seem to work (or be applied). I don't get the same `MaxWarningsExceededError` exception that I mentioned above.

**Comment by pehbehbeh** [comment]
I don't think there is much we can do about that problem. We are simply counting the errors we get from `sass-lint` and exit with an error code if there are any:

- https://github.com/sourceboat/sass-lint-vue/blob/develop/lib/reporter.js#L11
- https://github.com/sourceboat/sass-lint-vue/blob/develop/lib/reporter.js#L33

**Comment by stevehealy** [comment]
I see. That might be the issue so - I'm looking for warnings to generate an error - instead of just an error itself.
Would be a lovely addition though! :-)

**Comment by pehbehbeh** [comment]
Feel free to open a PR.
