### ISSUE TITLE
Disable Linter via Source

### ISSUE THREAD

**Issue by DapperFox** [sourceboat/sass-lint-vue#6]
I have class names in my code base that I can't control. I would like to be able to disable a certain rule in that file, but not universally in my project. `sass-lint` has a way to do this:
https://github.com/sasstools/sass-lint#disabling-linters-via-source
When I use `sass-lint-vue` I do not get any results.

![disable comment](https://user-images.githubusercontent.com/2700294/31292397-13a589c4-aa88-11e7-96a7-dc16d119f6bb.png)

![lint errors](https://user-images.githubusercontent.com/2700294/31291923-48f07f64-aa86-11e7-918f-67d56dcbe998.png)

I have tried disabling all rules or just disabling a specific rule and I can't get either functionality to work.

**Comment by krns** [comment]
Try disabling the rule or all rules via `// sass-lint:disable-all` instead of `// scss-lint:disable-all`.

Maybe we should add this to the readme.
